In [1]:
import numpy as np
import torch

# 1. Basic Matrix Operations with NumPy and PyTorch

# 1.1  NumPy Arithmetic

In [2]:
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[-1,1], [1,-1], [-1,1]])

In [3]:
# 1
A+B

array([[0, 3],
       [4, 3],
       [4, 7]])

In [4]:
# 2
A*B

array([[-1,  2],
       [ 3, -4],
       [-5,  6]])

In [5]:
# 3
A.T.dot(B)

array([[-3,  3],
       [-4,  4]])

In [6]:
# 4
A.dot(B.T)

array([[ 1, -1,  1],
       [ 1, -1,  1],
       [ 1, -1,  1]])

In [8]:
# 5
print('impossible - as the shapes dont allow multiplication - 3x2, 3,2')
A.dot(B)

impossible - as the shapes dont allow multiplication - 3x2, 3,2


ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

## 1.2 PyTorch Arithmetic

In [9]:
A = torch.tensor([[1,2], [3,4], [5,6]])
B = torch.tensor([[-1,1], [1,-1], [-1,1]])

In [22]:
# 1
print('A+B')
print(A+B)

print('\nA o B')
print(A*B)

print('\nA.T.B')
print(torch.mm(torch.transpose(A,0,1),B))

print('\nAB - impossible, as sizes don\'t match for matrix multiplication')
print(torch.mm(A,B))

A+B
tensor([[0, 3],
        [4, 3],
        [4, 7]])

A o B
tensor([[-1,  2],
        [ 3, -4],
        [-5,  6]])

A.T.B
tensor([[-3,  3],
        [-4,  4]])

AB - impossible, as sizes don't match for matrix multiplication


RuntimeError: size mismatch, m1: [3 x 2], m2: [3 x 2] at /opt/conda/conda-bld/pytorch_1573049310284/work/aten/src/TH/generic/THTensorMath.cpp:197